version: '2'

volumes:
  app-media: {}
  db-data: {}

services:
  lwt-app:
    image: noahzh89/lwt:1.6.2-7.3.1-apache-stretch
    links:
      - lwt-db:mysql
    volumes:
      - app-media:/var/www/html/media
    depends_on:
      - lwt-db
    ports:
      - 7070:80
  lwt-db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=lwtdbrootpassword
      - MYSQL_DATABASE=learning-with-texts
      - MYSQL_USER=lwt
      - MYSQL_PASSWORD=lwt
    volumes:
      - db-data:/var/lib/mysql
